import { useState } from "react";
import Head from "next/head";
import { ToastContainer } from "react-toastify";

import Container from "../styles/home";
import useShortlink from "../applications/useShortlink";

export default function Home(props) {
  const { listLink, addShortlink } = useShortlink();

  const [state, setState] = useState({
    valid: false,
    url: "",
  });

  function validateUrl(e) {
    e.preventDefault();
    if (state.url) {
      setState((prev) => ({ ...prev, valid: true }));
    }
  }

  async function newShortlink() {
    try {
      await addShortlink(state.url);
      setState((prev) => ({
        ...prev,
        url: "",
        valid: false,
      }));
    } catch (error) {}
  }
  return (
    <Container>
      <ToastContainer />
      <Head>
        <title>Shortlink Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <form className="items center" onSubmit={validateUrl}>
          <div className="input">
            <input
              placeholder="input url : https://google.com"
              type="url"
              name="url"
              pattern="https://.*"
              className="input"
              value={state.url}
              onChange={({ target: { value } }) =>
                setState((prev) => ({ ...prev, valid: false, url: value }))
              }
            />
            <div className="containerButton">
              <button
                type="button"
                disabled={!state.valid}
                onClick={newShortlink}
              >
                Generate
              </button>
              <button type="submit">Validate</button>
            </div>
          </div>
        </form>
        <div style={{ display: "flex" }} className="center">
          <div className="pager" />
        </div>
        <div className="items center" style={{ margin: "0px 20px" }}>
          <p>My Shortlink</p>
          <table>
            <tr>
              <th>URL</th>
              <th>Short</th>
            </tr>
            {listLink.map((i) => (
              <tr key={i.id}>
                <td>
                  <a className="spreadLink" href={i.url}>
                    {i.url}
                  </a>
                </td>
                <td>
                  <a
                    className="spreadLink"
                    href={`${props.basePath}${i.id}`}
                  >{`${props.basePath}${i.id}`}</a>
                </td>
              </tr>
            ))}
          </table>
        </div>
      </div>
    </Container>
  );
}

export async function getServerSideProps() {
  const basePath = process.env.VERCEL_URL || "http://localhost:3000/";

  return { props: { basePath } };
}
